# Generated by Django 3.1.5 on 2021-01-29 02:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0007_card_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 1, 29, 2, 25, 57, 126407)),
        ),
    ]
