# Generated by Django 3.1.5 on 2021-01-29 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0008_auto_20210129_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2021, 1, 29, 2, 29, 51, 287867, tzinfo=utc)),
        ),
    ]
