# Generated by Django 3.1.5 on 2021-01-29 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0009_auto_20210129_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
