# Generated by Django 3.1.5 on 2021-01-29 03:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0010_auto_20210129_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 3, 52, 12, 951217, tzinfo=utc)),
        ),
    ]
