# Generated by Django 3.1.5 on 2021-01-29 03:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('flashapp', '0011_auto_20210129_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 3, 54, 52, 17083, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_updated',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 29, 3, 54, 52, 17101, tzinfo=utc)),
        ),
    ]
